/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockmy_sqrt.h"

static const char* CMockString_my_sqrt = "my_sqrt";
static const char* CMockString_x = "x";

typedef struct _CMOCK_my_sqrt_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  double ReturnVal;
  double Expected_x;

} CMOCK_my_sqrt_CALL_INSTANCE;

static struct Mockmy_sqrtInstance
{
  CMOCK_MEM_INDEX_TYPE my_sqrt_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockmy_sqrt_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.my_sqrt_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_my_sqrt);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockmy_sqrt_Init(void)
{
  Mockmy_sqrt_Destroy();
}

void Mockmy_sqrt_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

double my_sqrt(double x)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_my_sqrt_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_my_sqrt);
  cmock_call_instance = (CMOCK_my_sqrt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.my_sqrt_CallInstance);
  Mock.my_sqrt_CallInstance = CMock_Guts_MemNext(Mock.my_sqrt_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_my_sqrt,CMockString_x);
    UNITY_TEST_ASSERT_EQUAL_FLOAT(cmock_call_instance->Expected_x, x, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_my_sqrt(CMOCK_my_sqrt_CALL_INSTANCE* cmock_call_instance, double x);
void CMockExpectParameters_my_sqrt(CMOCK_my_sqrt_CALL_INSTANCE* cmock_call_instance, double x)
{
  cmock_call_instance->Expected_x = x;
}

void my_sqrt_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, double x, double cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_my_sqrt_CALL_INSTANCE));
  CMOCK_my_sqrt_CALL_INSTANCE* cmock_call_instance = (CMOCK_my_sqrt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.my_sqrt_CallInstance = CMock_Guts_MemChain(Mock.my_sqrt_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_my_sqrt(cmock_call_instance, x);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

